### NumPy Basics

-  The most basic element of NumPy is `ndArray` or a simple `array`. which is **n-diamentional** and **homogenous** array. Basically al elements in NumPy array is the same data type which is integer or a float.

#### Import the NumPy library before use

In [1]:
import numpy as np

-  Creating the n-diamentional array using list

In [4]:
#1-D array uisng Numpy
array_1d = np.array([1,2,3,4,5,6])
print(array_1d)

[1 2 3 4 5 6]


In [5]:
#2-D array using NumPy
array_2d = np.array([[1,2,3,4],[5,8,9,7]])
print(array_2d)

[[1 2 3 4]
 [5 8 9 7]]


-  In Numpy array diamentions are called `Axes`. In numpy 2-D array
    -  `axis = 0` refers to a rows
    -  `axis = 0` refers to a columns

#### Advantages fo NumPy:

-  You can write vectorised code using NumPy array but not on list, which is **convenient to read and write, and concise.**
-  NumPy is much **faster** than convetional way of computations.

-  Say you have two lists of numbers, and want to calculate the element-wise product. The standard python list way would need you to map a lambda function (or worse - write a for loop), whereas with NumPy, you simply multiply the arrays.

In [6]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

# the list way to do it: map a function to the two lists
product_list = list(map(lambda x, y: x*y, list_1, list_2))
print(product_list)

[12, 30, 7, 35]


In [7]:
# The numpy array way to do it: simply multiply the two arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)

array_3 = array_1*array_2
print(array_3)
print(type(array_3))

[12 30  7 35]
<class 'numpy.ndarray'>


In [8]:
# Square a list
list_squared = [i**2 for i in list_1]

# Square a numpy array
array_squared = array_1**2

print(list_squared)
print(array_squared)

[9, 36, 49, 25]
[ 9 36 49 25]


### Creating NumPy array:

There are multiple ways to create numpy arrays, the most commmon ones being:

-  Convert lists or tuples to arrays using `np.array()`, as done above
-  Initialise arrays of fixed size (when the size is known).

In [9]:
# convert the list to a numpy array
array_from_list = np.array([1,2,3,4,5])

#convert the tupple to a numpy array
array_from_tupple = np.array((1,2,3,4,5))

print(array_from_list)
print(array_from_tupple)

[1 2 3 4 5]
[1 2 3 4 5]


-  Following ways are most commonly used:
    -  `np.ones` : create array of 1
    -  `np.zero` : create array of 0
    -  `np.random.random()` : create array of random numbers
    * ```np.arange()```: Create array with increments of a fixed step size
    * ```np.linspace()```: Create array of fixed length<br><br>
    
-  Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

    -  `np.full()`: Create a constant array of any number ‘n’
    -  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
    -  `np.eye()`: Create an identity matrix of any dimension
    -  `np.random.randint()`: Create a random array of integers within a particular range

In [11]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


-  when creating the numpy array it automatically intialized as float64. So, we have to explicitely provide the data type as given below.

In [12]:
print(np.ones((4,3), dtype = np.int))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
print(np.zeros((4,2), dtype = np.int))

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [16]:
print(np.random.random([3,5]))

[[0.70036603 0.05593119 0.8944478  0.21888885 0.36501228]
 [0.51737527 0.70202805 0.62815033 0.48027698 0.96874429]
 [0.72784574 0.60967535 0.87108255 0.74016306 0.87175379]]


In [17]:
# np.arange()
# np.arange() is the numpy equivalent of range()
# Notice that 10 is included, 100 is not, as in standard python lists

# From 10 to 100 with a step of 5
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [18]:
# np.linspace()
# Sometimes, you know the length of the array, not the step size

# Array of length 25 between 15 and 18
np.linspace(15, 18, 25)

array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

In [19]:
#np.full function : it create array of give value in second postion and place this value at all the positions
print(np.full((3,2),2))

[[2 2]
 [2 2]
 [2 2]]


In [21]:
#np.tile function :  it repeat given array with given number of times
# np.tile((array), Number of times to repeat)
print(np.tile(([1,2,3,4,5]),2))


[1 2 3 4 5 1 2 3 4 5]


In [24]:
#np.eye() :  it return the array of 1's with diagonal and rest of 0's

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
print(np.arange(5,55,5))

[ 5 10 15 20 25 30 35 40 45 50]


In [34]:
print(np.tile(([1,0]),(2,2)))

[[1 0 1 0]
 [1 0 1 0]]


In [4]:
a = [[1,0],[0,1]]
np.tile(a,(4//2,4//2))

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [51]:
list_1 = [10,11,12,13]
list_2 = [15,12,13,14]

array_1 = np.array((list_1+list_2)).reshape(2,4)
print(array_1.shape)
print(array_1.ndim)


(2, 4)
2


### Inspect the Structure and Content of Arrays

-  following functions are helpfull to inspect the array of large ammount of data
    -  `array.shape` : Give the shape of array(nXm)
    -  `array.dtype` : data type of element of the array
    -  `array.ndim`  : number of diamentions or axes of the array
    -  `array.itemsize` : memory used by each array element in byte.

In [55]:
# print aray of random number of size(1000,200)

array_1 = np.random.random((1000,200))
print(array_1[0,])

[4.76913174e-01 1.36561876e-01 6.50835064e-01 7.03034067e-01
 8.24210548e-02 8.03975225e-01 2.14963887e-01 5.08837016e-01
 6.74630731e-01 6.76799424e-01 4.25741707e-01 9.59564847e-01
 9.51941993e-01 3.32073584e-01 8.27775676e-01 6.05159008e-01
 8.45509639e-01 5.07198715e-01 9.61485896e-01 1.16480395e-01
 4.36144535e-01 3.07446760e-01 6.11531715e-01 5.01419776e-01
 4.84326020e-01 5.93037946e-01 3.17505234e-01 6.91791237e-01
 9.58098624e-01 9.15009848e-01 7.95075857e-01 6.08136905e-01
 7.57987254e-01 3.27028020e-01 1.76549107e-01 8.20495047e-01
 9.85359639e-02 7.61039295e-01 8.76612600e-01 7.13314245e-02
 1.47246414e-01 6.24706672e-02 2.15764162e-01 8.20293522e-01
 8.18873879e-01 7.21636050e-01 1.22704410e-01 6.52804200e-01
 7.22496854e-01 1.65437852e-01 7.18434792e-01 6.65098164e-01
 9.56735501e-01 9.39389677e-01 9.64292448e-01 7.27453527e-01
 3.18931422e-01 6.31847380e-01 3.70529145e-01 9.62067449e-01
 2.86864969e-01 3.77979768e-01 4.26187459e-01 2.76737915e-01
 3.28485652e-01 1.926063

In [65]:
print("shape of the array is:    {}". format(array_1.shape))
print("diamentions of the array: {}". format(array_1.ndim))
print("itemsize of the array:    {}". format(array_1.itemsize))
print("data type of the array:   {}". format(array_1.dtype))

shape of the array is:    (1000, 200)
diamentions of the array: 2
itemsize of the array:    8
data type of the array:   float64


Reading 3-D arrays is not very obvious, because we can only print maximum two dimensions on paper, and thus they are printed according to a specific convention. Printing higher dimensional arrays follows the following conventions:
* The last axis is printed from left to right
* The second-to-last axis is printed from top to bottom
* The other axes are also printed top-to-bottom, with each slice separated by another using an empty line 

Let's see some examples.

In [66]:
print(np.arange(24).reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Subset, Slice, Index and Iterate through Arrays

For **one-dimensional arrays**, indexing, slicing etc. is **similar to python lists** - indexing starts at 0.

In [5]:
array_1 = np.array([1,2,3,5,4,6,7,8,5,3,2])
print(array_1[0::2])

[1 3 4 7 5 2]


In [7]:
# Indexing and slicing one dimensional arrays
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# Third element
print(array_1d[2])

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 1]])

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])

2
[2 5 1]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


In [13]:
# Iterations are also similar to lists
for a in array_1d:
    print(a**2)

0
1
4
9
16
25
36
49
64
81


### Multidimesional Array:

-  Multidimensional array are indexed using the as many indices as number of diamentions or axes
-  For 2-D array we reuired `array[x,y]` indexes
-  Each axes is start from 0

-  Creating the 2-D array

In [4]:
array_2D = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(array_2D)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]


In [24]:
test_list = [[1,2,3,4],[5,6,7,8],[9,8,7,6]]
print(test_list)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 6]]


-  Access and slice elements of 2-D array

In [5]:
# this prints the element of 3rd row and 3rd column 
print(array_2D[2,2])

7


In [18]:
#it prints the elements of full 2nd row 
print(array_2D[:,1])

[2 6 8]


In [13]:
# it print all column in 3rd row
print(array_2D[:,2])

[3 7 7]


In [15]:
# below code print the 1th to last column of 2nd to last row
print(array_2D[1:,:2])

[[5 6]
 [9 8]]


In [17]:
for row in array_2D:
    for col in row:
        print(col)

1
2
3
4
5
6
7
8
9
8
7
6


In [56]:
array = np.array([[1],
 [2],
 [3],
 [4],
 [5]])
print(array)


[[1]
 [2]
 [3]
 [4]
 [5]]


In [61]:
print(array[:,0])
print(array[0,:])
print(array[:,-1])
print(array[-1,:])

print((array[:,-1:]))
print((array[-1:,:])[0])

[1 2 3 4 5]
[1]
[1 2 3 4 5]
[5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[5]


In [14]:
import numpy as np

array_1 = np.random.random((11,12))
array_1

array([[0.16884441, 0.40014835, 0.79942942, 0.49244846, 0.32690845,
        0.2293067 , 0.91801727, 0.10505764, 0.90940533, 0.52612325,
        0.42827235, 0.83689013],
       [0.35994314, 0.26081342, 0.93368861, 0.48766715, 0.67385545,
        0.4581962 , 0.15737589, 0.61057552, 0.35773349, 0.55033701,
        0.77338028, 0.74019293],
       [0.16125448, 0.3154995 , 0.23199676, 0.73959356, 0.50496812,
        0.16251132, 0.22478063, 0.27009794, 0.63502203, 0.76702446,
        0.26309352, 0.89061889],
       [0.4697855 , 0.69935247, 0.33288193, 0.47354069, 0.00103809,
        0.2175661 , 0.10047827, 0.33358775, 0.56637786, 0.38117828,
        0.41720792, 0.04023318],
       [0.37938607, 0.37171657, 0.77171919, 0.6053494 , 0.52981956,
        0.13396685, 0.51497044, 0.20508786, 0.58788921, 0.96826832,
        0.91777341, 0.17074427],
       [0.77222404, 0.84814809, 0.175792  , 0.33275123, 0.80151358,
        0.9376315 , 0.10159564, 0.02288698, 0.59131199, 0.30133725,
        0.71124928,

In [12]:
np.unravel_index(99, (11,12)) 

(8, 3)

In [19]:
print(array_1[:,:3])

[[0.16884441 0.40014835 0.79942942]
 [0.35994314 0.26081342 0.93368861]
 [0.16125448 0.3154995  0.23199676]
 [0.4697855  0.69935247 0.33288193]
 [0.37938607 0.37171657 0.77171919]
 [0.77222404 0.84814809 0.175792  ]
 [0.65958493 0.0599824  0.2266357 ]
 [0.37646831 0.47995876 0.17368184]
 [0.93535716 0.58188126 0.81340734]
 [0.89438095 0.59035777 0.32126798]
 [0.62643038 0.95345398 0.13516195]]


In [39]:
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]


In [41]:
a_swap = a[2]
a[2] = a[1]
a[1] = a_swap
print(a)

[[4 3 1]
 [9 9 3]
 [9 9 3]
 [8 2 4]]


In [92]:
n=7
a = np.zeros((n,n), dtype = np.int)
a[0:1,:] = 1
a[-1:,:] = 1
a[:,0:1] = 1
a[:,-1:] = 1
print(a)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [103]:
n=4
a = np.ones((n,n), dtype = np.int)
a[1:-1,1:-1] = 0 
a

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [6]:
list_1 = [2,3,4,5] 
list_2 = [7,8,9,6] 

arr1 = np.array(list_1)
arr2 = np.array(list_2)

arr3 = np.ravel()

TypeError: ravel() missing 1 required positional argument: 'a'

In [5]:
rows_m = 2
cols_n =3
array_x = np.ones((rows_m,cols_n),dtype = np.int)
array_x

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
int_x = 1
rows_m = 2
cols_n =3
array_x = np.full((rows_m,cols_n),int_x,dtype = np.int)
array_x

array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
import numpy as np
n = 4
array1 = np.tile([0,1],(n,n))
print (array1)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [3]:
a = [[1,0],[0,1]]
np.tile(a,(4//2,4//2))

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [7]:
help(np.tiles)

AttributeError: module 'numpy' has no attribute 'tiles'